# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ywkim/mntdisk/samsung/gen2/agent

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ywkim/mntdisk/samsung/gen2/agent

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ywkim/mntdisk/samsung/gen2/agent/CMakeFiles /home/ywkim/mntdisk/samsung/gen2/agent/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ywkim/mntdisk/samsung/gen2/agent/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named agent

# Build rule for target.
agent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 agent
.PHONY : agent

# fast build rule for target.
agent/fast:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/build
.PHONY : agent/fast

src/ServerSocket.o: src/ServerSocket.cpp.o
.PHONY : src/ServerSocket.o

# target to build an object file
src/ServerSocket.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/ServerSocket.cpp.o
.PHONY : src/ServerSocket.cpp.o

src/ServerSocket.i: src/ServerSocket.cpp.i
.PHONY : src/ServerSocket.i

# target to preprocess a source file
src/ServerSocket.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/ServerSocket.cpp.i
.PHONY : src/ServerSocket.cpp.i

src/ServerSocket.s: src/ServerSocket.cpp.s
.PHONY : src/ServerSocket.s

# target to generate assembly for a file
src/ServerSocket.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/ServerSocket.cpp.s
.PHONY : src/ServerSocket.cpp.s

src/Socket.o: src/Socket.cpp.o
.PHONY : src/Socket.o

# target to build an object file
src/Socket.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/Socket.cpp.o
.PHONY : src/Socket.cpp.o

src/Socket.i: src/Socket.cpp.i
.PHONY : src/Socket.i

# target to preprocess a source file
src/Socket.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/Socket.cpp.i
.PHONY : src/Socket.cpp.i

src/Socket.s: src/Socket.cpp.s
.PHONY : src/Socket.s

# target to generate assembly for a file
src/Socket.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/Socket.cpp.s
.PHONY : src/Socket.cpp.s

src/device.o: src/device.cpp.o
.PHONY : src/device.o

# target to build an object file
src/device.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/device.cpp.o
.PHONY : src/device.cpp.o

src/device.i: src/device.cpp.i
.PHONY : src/device.i

# target to preprocess a source file
src/device.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/device.cpp.i
.PHONY : src/device.cpp.i

src/device.s: src/device.cpp.s
.PHONY : src/device.s

# target to generate assembly for a file
src/device.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/device.cpp.s
.PHONY : src/device.cpp.s

src/msg.o: src/msg.cpp.o
.PHONY : src/msg.o

# target to build an object file
src/msg.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/msg.cpp.o
.PHONY : src/msg.cpp.o

src/msg.i: src/msg.cpp.i
.PHONY : src/msg.i

# target to preprocess a source file
src/msg.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/msg.cpp.i
.PHONY : src/msg.cpp.i

src/msg.s: src/msg.cpp.s
.PHONY : src/msg.s

# target to generate assembly for a file
src/msg.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/msg.cpp.s
.PHONY : src/msg.cpp.s

src/object.o: src/object.cpp.o
.PHONY : src/object.o

# target to build an object file
src/object.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/object.cpp.o
.PHONY : src/object.cpp.o

src/object.i: src/object.cpp.i
.PHONY : src/object.i

# target to preprocess a source file
src/object.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/object.cpp.i
.PHONY : src/object.cpp.i

src/object.s: src/object.cpp.s
.PHONY : src/object.s

# target to generate assembly for a file
src/object.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/object.cpp.s
.PHONY : src/object.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/server.o: src/server.cpp.o
.PHONY : src/server.o

# target to build an object file
src/server.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/server.cpp.o
.PHONY : src/server.cpp.o

src/server.i: src/server.cpp.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/server.cpp.i
.PHONY : src/server.cpp.i

src/server.s: src/server.cpp.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/server.cpp.s
.PHONY : src/server.cpp.s

src/task.o: src/task.cpp.o
.PHONY : src/task.o

# target to build an object file
src/task.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/task.cpp.o
.PHONY : src/task.cpp.o

src/task.i: src/task.cpp.i
.PHONY : src/task.i

# target to preprocess a source file
src/task.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/task.cpp.i
.PHONY : src/task.cpp.i

src/task.s: src/task.cpp.s
.PHONY : src/task.s

# target to generate assembly for a file
src/task.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/task.cpp.s
.PHONY : src/task.cpp.s

src/thread.o: src/thread.cpp.o
.PHONY : src/thread.o

# target to build an object file
src/thread.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/thread.cpp.o
.PHONY : src/thread.cpp.o

src/thread.i: src/thread.cpp.i
.PHONY : src/thread.i

# target to preprocess a source file
src/thread.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/thread.cpp.i
.PHONY : src/thread.cpp.i

src/thread.s: src/thread.cpp.s
.PHONY : src/thread.s

# target to generate assembly for a file
src/thread.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/thread.cpp.s
.PHONY : src/thread.cpp.s

src/timer.o: src/timer.cpp.o
.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i
.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s
.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/work.o: src/work.cpp.o
.PHONY : src/work.o

# target to build an object file
src/work.cpp.o:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/work.cpp.o
.PHONY : src/work.cpp.o

src/work.i: src/work.cpp.i
.PHONY : src/work.i

# target to preprocess a source file
src/work.cpp.i:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/work.cpp.i
.PHONY : src/work.cpp.i

src/work.s: src/work.cpp.s
.PHONY : src/work.s

# target to generate assembly for a file
src/work.cpp.s:
	$(MAKE) -f CMakeFiles/agent.dir/build.make CMakeFiles/agent.dir/src/work.cpp.s
.PHONY : src/work.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... agent"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... src/ServerSocket.o"
	@echo "... src/ServerSocket.i"
	@echo "... src/ServerSocket.s"
	@echo "... src/Socket.o"
	@echo "... src/Socket.i"
	@echo "... src/Socket.s"
	@echo "... src/device.o"
	@echo "... src/device.i"
	@echo "... src/device.s"
	@echo "... src/msg.o"
	@echo "... src/msg.i"
	@echo "... src/msg.s"
	@echo "... src/object.o"
	@echo "... src/object.i"
	@echo "... src/object.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/task.o"
	@echo "... src/task.i"
	@echo "... src/task.s"
	@echo "... src/thread.o"
	@echo "... src/thread.i"
	@echo "... src/thread.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/work.o"
	@echo "... src/work.i"
	@echo "... src/work.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

